name: Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NIXPKGS_ALLOW_UNFREE: 1
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=
      - run: nix-shell --run "hardhat compile && hardhat test"
