name: Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NIXPKGS_ALLOW_UNFREE: 1
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=fa5e153653a1b48e4a21a14b341e2e01835ba8b5
      - run: nix-shell --run "hardhat compile && hardhat test"
